// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityHistory.Infrastructure.Data;

#nullable disable

namespace UniversityHistory.Infrastructure.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20260328225828_SeedMoreData")]
    partial class SeedMoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityHistory.Domain.Entities.AcademicLeave", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("leave_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("LeaveId");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("Academic_Leave", (string)null);

                    b.HasData(
                        new
                        {
                            LeaveId = 1,
                            EnrollmentId = 4,
                            Reason = "Medical leave",
                            StartDate = new DateOnly(2023, 1, 16)
                        },
                        new
                        {
                            LeaveId = 2,
                            EndDate = new DateOnly(2024, 2, 10),
                            EnrollmentId = 8,
                            Reason = "Internship pause",
                            StartDate = new DateOnly(2023, 11, 10)
                        },
                        new
                        {
                            LeaveId = 3,
                            EnrollmentId = 9,
                            Reason = "Family circumstances",
                            StartDate = new DateOnly(2025, 2, 1)
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineId"));

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("discipline_name");

                    b.HasKey("DisciplineId");

                    b.ToTable("Discipline", (string)null);

                    b.HasData(
                        new
                        {
                            DisciplineId = 1,
                            DisciplineName = "Calculus I"
                        },
                        new
                        {
                            DisciplineId = 2,
                            DisciplineName = "Introduction to Computer Science"
                        },
                        new
                        {
                            DisciplineId = 3,
                            DisciplineName = "Data Structures"
                        },
                        new
                        {
                            DisciplineId = 4,
                            DisciplineName = "Linear Algebra"
                        },
                        new
                        {
                            DisciplineId = 5,
                            DisciplineName = "Discrete Mathematics"
                        },
                        new
                        {
                            DisciplineId = 6,
                            DisciplineName = "Databases"
                        },
                        new
                        {
                            DisciplineId = 7,
                            DisciplineName = "Operating Systems"
                        },
                        new
                        {
                            DisciplineId = 8,
                            DisciplineName = "Computer Networks"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.ExternalTransfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transfer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferId"));

                    b.Property<int?>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("institution_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("notes");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateOnly>("TransferDate")
                        .HasColumnType("date")
                        .HasColumnName("transfer_date");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("transfer_type");

                    b.HasKey("TransferId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("StudentId");

                    b.ToTable("External_Transfers", null, t =>
                        {
                            t.HasCheckConstraint("chk_transfer_type", "transfer_type IN ('In','Out')");
                        });

                    b.HasData(
                        new
                        {
                            TransferId = 1,
                            EnrollmentId = 5,
                            InstitutionId = 2,
                            Notes = "Completed first year at Stanford",
                            StudentId = 4,
                            TransferDate = new DateOnly(2023, 8, 25),
                            TransferType = "In"
                        },
                        new
                        {
                            TransferId = 2,
                            EnrollmentId = 12,
                            InstitutionId = 3,
                            Notes = "Transferred after first semester",
                            StudentId = 11,
                            TransferDate = new DateOnly(2024, 8, 20),
                            TransferType = "In"
                        },
                        new
                        {
                            TransferId = 3,
                            EnrollmentId = 13,
                            InstitutionId = 4,
                            Notes = "Started master's program",
                            StudentId = 12,
                            TransferDate = new DateOnly(2024, 7, 1),
                            TransferType = "Out"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.GradeRecord", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<DateOnly>("AssessmentDate")
                        .HasColumnType("date")
                        .HasColumnName("assessment_date");

                    b.Property<int>("CourseEnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("course_enrollment_id");

                    b.Property<string>("GradeValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("grade_value");

                    b.HasKey("GradeId");

                    b.HasIndex("CourseEnrollmentId")
                        .IsUnique();

                    b.ToTable("Grade_Record", (string)null);

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            AssessmentDate = new DateOnly(2022, 1, 15),
                            CourseEnrollmentId = 1,
                            GradeValue = "95"
                        },
                        new
                        {
                            GradeId = 2,
                            AssessmentDate = new DateOnly(2022, 1, 18),
                            CourseEnrollmentId = 2,
                            GradeValue = "88"
                        },
                        new
                        {
                            GradeId = 3,
                            AssessmentDate = new DateOnly(2022, 1, 15),
                            CourseEnrollmentId = 3,
                            GradeValue = "91"
                        },
                        new
                        {
                            GradeId = 4,
                            AssessmentDate = new DateOnly(2022, 6, 10),
                            CourseEnrollmentId = 4,
                            GradeValue = "89"
                        },
                        new
                        {
                            GradeId = 5,
                            AssessmentDate = new DateOnly(2022, 6, 14),
                            CourseEnrollmentId = 5,
                            GradeValue = "84"
                        },
                        new
                        {
                            GradeId = 6,
                            AssessmentDate = new DateOnly(2022, 1, 16),
                            CourseEnrollmentId = 7,
                            GradeValue = "90"
                        },
                        new
                        {
                            GradeId = 7,
                            AssessmentDate = new DateOnly(2022, 6, 12),
                            CourseEnrollmentId = 8,
                            GradeValue = "86"
                        },
                        new
                        {
                            GradeId = 8,
                            AssessmentDate = new DateOnly(2022, 6, 15),
                            CourseEnrollmentId = 9,
                            GradeValue = "79"
                        },
                        new
                        {
                            GradeId = 9,
                            AssessmentDate = new DateOnly(2024, 1, 20),
                            CourseEnrollmentId = 10,
                            GradeValue = "92"
                        },
                        new
                        {
                            GradeId = 10,
                            AssessmentDate = new DateOnly(2024, 1, 22),
                            CourseEnrollmentId = 11,
                            GradeValue = "87"
                        },
                        new
                        {
                            GradeId = 11,
                            AssessmentDate = new DateOnly(2023, 1, 18),
                            CourseEnrollmentId = 13,
                            GradeValue = "81"
                        },
                        new
                        {
                            GradeId = 12,
                            AssessmentDate = new DateOnly(2023, 1, 20),
                            CourseEnrollmentId = 14,
                            GradeValue = "85"
                        },
                        new
                        {
                            GradeId = 13,
                            AssessmentDate = new DateOnly(2023, 6, 19),
                            CourseEnrollmentId = 15,
                            GradeValue = "88"
                        },
                        new
                        {
                            GradeId = 14,
                            AssessmentDate = new DateOnly(2025, 1, 21),
                            CourseEnrollmentId = 17,
                            GradeValue = "93"
                        },
                        new
                        {
                            GradeId = 15,
                            AssessmentDate = new DateOnly(2025, 1, 23),
                            CourseEnrollmentId = 18,
                            GradeValue = "89"
                        },
                        new
                        {
                            GradeId = 16,
                            AssessmentDate = new DateOnly(2023, 1, 19),
                            CourseEnrollmentId = 20,
                            GradeValue = "76"
                        },
                        new
                        {
                            GradeId = 17,
                            AssessmentDate = new DateOnly(2023, 1, 22),
                            CourseEnrollmentId = 21,
                            GradeValue = "82"
                        },
                        new
                        {
                            GradeId = 18,
                            AssessmentDate = new DateOnly(2023, 6, 15),
                            CourseEnrollmentId = 22,
                            GradeValue = "80"
                        },
                        new
                        {
                            GradeId = 19,
                            AssessmentDate = new DateOnly(2023, 6, 20),
                            CourseEnrollmentId = 23,
                            GradeValue = "78"
                        },
                        new
                        {
                            GradeId = 20,
                            AssessmentDate = new DateOnly(2024, 12, 18),
                            CourseEnrollmentId = 24,
                            GradeValue = "84"
                        },
                        new
                        {
                            GradeId = 21,
                            AssessmentDate = new DateOnly(2025, 1, 28),
                            CourseEnrollmentId = 25,
                            GradeValue = "74"
                        },
                        new
                        {
                            GradeId = 22,
                            AssessmentDate = new DateOnly(2025, 1, 25),
                            CourseEnrollmentId = 26,
                            GradeValue = "83"
                        },
                        new
                        {
                            GradeId = 23,
                            AssessmentDate = new DateOnly(2025, 1, 24),
                            CourseEnrollmentId = 29,
                            GradeValue = "91"
                        },
                        new
                        {
                            GradeId = 24,
                            AssessmentDate = new DateOnly(2025, 1, 26),
                            CourseEnrollmentId = 30,
                            GradeValue = "88"
                        },
                        new
                        {
                            GradeId = 25,
                            AssessmentDate = new DateOnly(2022, 1, 18),
                            CourseEnrollmentId = 32,
                            GradeValue = "94"
                        },
                        new
                        {
                            GradeId = 26,
                            AssessmentDate = new DateOnly(2022, 1, 21),
                            CourseEnrollmentId = 33,
                            GradeValue = "90"
                        },
                        new
                        {
                            GradeId = 27,
                            AssessmentDate = new DateOnly(2022, 6, 16),
                            CourseEnrollmentId = 34,
                            GradeValue = "87"
                        },
                        new
                        {
                            GradeId = 28,
                            AssessmentDate = new DateOnly(2022, 6, 18),
                            CourseEnrollmentId = 35,
                            GradeValue = "85"
                        },
                        new
                        {
                            GradeId = 29,
                            AssessmentDate = new DateOnly(2024, 1, 15),
                            CourseEnrollmentId = 36,
                            GradeValue = "69"
                        },
                        new
                        {
                            GradeId = 30,
                            AssessmentDate = new DateOnly(2024, 1, 19),
                            CourseEnrollmentId = 37,
                            GradeValue = "72"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("institution_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("institution_name");

                    b.HasKey("InstitutionId");

                    b.ToTable("Institution", (string)null);

                    b.HasData(
                        new
                        {
                            InstitutionId = 1,
                            City = "Cambridge",
                            Country = "USA",
                            InstitutionName = "MIT"
                        },
                        new
                        {
                            InstitutionId = 2,
                            City = "Stanford",
                            Country = "USA",
                            InstitutionName = "Stanford University"
                        },
                        new
                        {
                            InstitutionId = 3,
                            City = "Kyiv",
                            Country = "Ukraine",
                            InstitutionName = "Kyiv Polytechnic Institute"
                        },
                        new
                        {
                            InstitutionId = 4,
                            City = "Lviv",
                            Country = "Ukraine",
                            InstitutionName = "Lviv Polytechnic"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.PlanDiscipline", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("control_type");

                    b.Property<decimal>("Credits")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("credits");

                    b.Property<int>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("hours");

                    b.Property<int>("SemesterNo")
                        .HasColumnType("int")
                        .HasColumnName("semester_no");

                    b.HasKey("PlanId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("Plan_Disciplines", null, t =>
                        {
                            t.HasCheckConstraint("chk_control_type", "control_type IN ('Exam','Credit','Coursework')");
                        });

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            DisciplineId = 1,
                            ControlType = "Exam",
                            Credits = 4.0m,
                            Hours = 120,
                            SemesterNo = 1
                        },
                        new
                        {
                            PlanId = 1,
                            DisciplineId = 2,
                            ControlType = "Exam",
                            Credits = 5.0m,
                            Hours = 150,
                            SemesterNo = 1
                        },
                        new
                        {
                            PlanId = 1,
                            DisciplineId = 5,
                            ControlType = "Credit",
                            Credits = 3.0m,
                            Hours = 90,
                            SemesterNo = 1
                        },
                        new
                        {
                            PlanId = 1,
                            DisciplineId = 3,
                            ControlType = "Coursework",
                            Credits = 6.0m,
                            Hours = 180,
                            SemesterNo = 2
                        },
                        new
                        {
                            PlanId = 1,
                            DisciplineId = 4,
                            ControlType = "Exam",
                            Credits = 4.0m,
                            Hours = 120,
                            SemesterNo = 2
                        },
                        new
                        {
                            PlanId = 1,
                            DisciplineId = 6,
                            ControlType = "Exam",
                            Credits = 5.0m,
                            Hours = 150,
                            SemesterNo = 3
                        },
                        new
                        {
                            PlanId = 1,
                            DisciplineId = 7,
                            ControlType = "Exam",
                            Credits = 5.0m,
                            Hours = 150,
                            SemesterNo = 4
                        },
                        new
                        {
                            PlanId = 2,
                            DisciplineId = 1,
                            ControlType = "Exam",
                            Credits = 4.0m,
                            Hours = 120,
                            SemesterNo = 1
                        },
                        new
                        {
                            PlanId = 2,
                            DisciplineId = 2,
                            ControlType = "Exam",
                            Credits = 5.0m,
                            Hours = 150,
                            SemesterNo = 1
                        },
                        new
                        {
                            PlanId = 2,
                            DisciplineId = 4,
                            ControlType = "Exam",
                            Credits = 4.0m,
                            Hours = 120,
                            SemesterNo = 2
                        },
                        new
                        {
                            PlanId = 2,
                            DisciplineId = 5,
                            ControlType = "Credit",
                            Credits = 3.0m,
                            Hours = 90,
                            SemesterNo = 2
                        },
                        new
                        {
                            PlanId = 2,
                            DisciplineId = 6,
                            ControlType = "Exam",
                            Credits = 5.0m,
                            Hours = 150,
                            SemesterNo = 3
                        },
                        new
                        {
                            PlanId = 2,
                            DisciplineId = 8,
                            ControlType = "Exam",
                            Credits = 5.0m,
                            Hours = 150,
                            SemesterNo = 4
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("StudentId");

                    b.ToTable("Student", null, t =>
                        {
                            t.HasCheckConstraint("chk_student_status", "status IN ('Active','OnLeave','Expelled','Graduated')");
                        });

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            BirthDate = new DateOnly(2003, 5, 14),
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Phone = "555-0101",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 2,
                            BirthDate = new DateOnly(2002, 11, 2),
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            Phone = "555-0102",
                            Status = "Graduated"
                        },
                        new
                        {
                            StudentId = 3,
                            BirthDate = new DateOnly(2004, 8, 22),
                            Email = "charlie@example.com",
                            FirstName = "Charlie",
                            LastName = "Williams",
                            Phone = "555-0103",
                            Status = "OnLeave"
                        },
                        new
                        {
                            StudentId = 4,
                            BirthDate = new DateOnly(2003, 1, 30),
                            Email = "diana@example.com",
                            FirstName = "Diana",
                            LastName = "Brown",
                            Phone = "555-0104",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 5,
                            BirthDate = new DateOnly(2003, 3, 2),
                            Email = "evan@example.com",
                            FirstName = "Evan",
                            LastName = "Davis",
                            Phone = "555-0105",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 6,
                            BirthDate = new DateOnly(2004, 2, 19),
                            Email = "fiona@example.com",
                            FirstName = "Fiona",
                            LastName = "Miller",
                            Phone = "555-0106",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 7,
                            BirthDate = new DateOnly(2002, 9, 9),
                            Email = "george@example.com",
                            FirstName = "George",
                            LastName = "Wilson",
                            Phone = "555-0107",
                            Status = "Graduated"
                        },
                        new
                        {
                            StudentId = 8,
                            BirthDate = new DateOnly(2004, 6, 10),
                            Email = "hannah@example.com",
                            FirstName = "Hannah",
                            LastName = "Moore",
                            Phone = "555-0108",
                            Status = "OnLeave"
                        },
                        new
                        {
                            StudentId = 9,
                            BirthDate = new DateOnly(2003, 12, 1),
                            Email = "ivan@example.com",
                            FirstName = "Ivan",
                            LastName = "Taylor",
                            Phone = "555-0109",
                            Status = "Expelled"
                        },
                        new
                        {
                            StudentId = 10,
                            BirthDate = new DateOnly(2005, 4, 11),
                            Email = "julia@example.com",
                            FirstName = "Julia",
                            LastName = "Anderson",
                            Phone = "555-0110",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 11,
                            BirthDate = new DateOnly(2004, 8, 5),
                            Email = "kevin@example.com",
                            FirstName = "Kevin",
                            LastName = "Thomas",
                            Phone = "555-0111",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 12,
                            BirthDate = new DateOnly(2002, 5, 23),
                            Email = "laura@example.com",
                            FirstName = "Laura",
                            LastName = "Jackson",
                            Phone = "555-0112",
                            Status = "Graduated"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentCourseEnrollment", b =>
                {
                    b.Property<int>("CourseEnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("course_enrollment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseEnrollmentId"));

                    b.Property<int>("AcademicYearStart")
                        .HasColumnType("int")
                        .HasColumnName("academic_year_start");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Planned'");

                    b.HasKey("CourseEnrollmentId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("Student_Course_Enrollment", null, t =>
                        {
                            t.HasCheckConstraint("chk_course_status", "status IN ('Planned','InProgress','Completed','Retake')");
                        });

                    b.HasData(
                        new
                        {
                            CourseEnrollmentId = 1,
                            AcademicYearStart = 2021,
                            AssignmentId = 1,
                            DisciplineId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 2,
                            AcademicYearStart = 2021,
                            AssignmentId = 1,
                            DisciplineId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 3,
                            AcademicYearStart = 2021,
                            AssignmentId = 2,
                            DisciplineId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 4,
                            AcademicYearStart = 2022,
                            AssignmentId = 1,
                            DisciplineId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 5,
                            AcademicYearStart = 2022,
                            AssignmentId = 1,
                            DisciplineId = 4,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 6,
                            AcademicYearStart = 2023,
                            AssignmentId = 1,
                            DisciplineId = 6,
                            Status = "InProgress"
                        },
                        new
                        {
                            CourseEnrollmentId = 7,
                            AcademicYearStart = 2021,
                            AssignmentId = 2,
                            DisciplineId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 8,
                            AcademicYearStart = 2022,
                            AssignmentId = 2,
                            DisciplineId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 9,
                            AcademicYearStart = 2022,
                            AssignmentId = 2,
                            DisciplineId = 4,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 10,
                            AcademicYearStart = 2023,
                            AssignmentId = 4,
                            DisciplineId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 11,
                            AcademicYearStart = 2023,
                            AssignmentId = 4,
                            DisciplineId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 12,
                            AcademicYearStart = 2024,
                            AssignmentId = 4,
                            DisciplineId = 4,
                            Status = "InProgress"
                        },
                        new
                        {
                            CourseEnrollmentId = 13,
                            AcademicYearStart = 2022,
                            AssignmentId = 5,
                            DisciplineId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 14,
                            AcademicYearStart = 2022,
                            AssignmentId = 5,
                            DisciplineId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 15,
                            AcademicYearStart = 2023,
                            AssignmentId = 5,
                            DisciplineId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 16,
                            AcademicYearStart = 2024,
                            AssignmentId = 5,
                            DisciplineId = 6,
                            Status = "Planned"
                        },
                        new
                        {
                            CourseEnrollmentId = 17,
                            AcademicYearStart = 2024,
                            AssignmentId = 6,
                            DisciplineId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 18,
                            AcademicYearStart = 2024,
                            AssignmentId = 6,
                            DisciplineId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 19,
                            AcademicYearStart = 2025,
                            AssignmentId = 6,
                            DisciplineId = 4,
                            Status = "InProgress"
                        },
                        new
                        {
                            CourseEnrollmentId = 20,
                            AcademicYearStart = 2022,
                            AssignmentId = 7,
                            DisciplineId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 21,
                            AcademicYearStart = 2022,
                            AssignmentId = 7,
                            DisciplineId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 22,
                            AcademicYearStart = 2023,
                            AssignmentId = 7,
                            DisciplineId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 23,
                            AcademicYearStart = 2023,
                            AssignmentId = 7,
                            DisciplineId = 4,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 24,
                            AcademicYearStart = 2024,
                            AssignmentId = 7,
                            DisciplineId = 6,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 25,
                            AcademicYearStart = 2024,
                            AssignmentId = 8,
                            DisciplineId = 1,
                            Status = "Retake"
                        },
                        new
                        {
                            CourseEnrollmentId = 26,
                            AcademicYearStart = 2024,
                            AssignmentId = 8,
                            DisciplineId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 27,
                            AcademicYearStart = 2025,
                            AssignmentId = 9,
                            DisciplineId = 1,
                            Status = "InProgress"
                        },
                        new
                        {
                            CourseEnrollmentId = 28,
                            AcademicYearStart = 2025,
                            AssignmentId = 9,
                            DisciplineId = 5,
                            Status = "Planned"
                        },
                        new
                        {
                            CourseEnrollmentId = 29,
                            AcademicYearStart = 2024,
                            AssignmentId = 10,
                            DisciplineId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 30,
                            AcademicYearStart = 2024,
                            AssignmentId = 10,
                            DisciplineId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 31,
                            AcademicYearStart = 2025,
                            AssignmentId = 10,
                            DisciplineId = 8,
                            Status = "InProgress"
                        },
                        new
                        {
                            CourseEnrollmentId = 32,
                            AcademicYearStart = 2021,
                            AssignmentId = 11,
                            DisciplineId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 33,
                            AcademicYearStart = 2021,
                            AssignmentId = 11,
                            DisciplineId = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 34,
                            AcademicYearStart = 2022,
                            AssignmentId = 11,
                            DisciplineId = 3,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 35,
                            AcademicYearStart = 2022,
                            AssignmentId = 11,
                            DisciplineId = 4,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 36,
                            AcademicYearStart = 2023,
                            AssignmentId = 12,
                            DisciplineId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 37,
                            AcademicYearStart = 2023,
                            AssignmentId = 12,
                            DisciplineId = 2,
                            Status = "Retake"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentGroupEnrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("ReasonEnd")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("reason_end");

                    b.Property<string>("ReasonStart")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("reason_start");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("GroupId", "DateFrom")
                        .HasDatabaseName("IX_Enrollment_GroupId_DateFrom");

                    b.ToTable("Student_Group_Enrollment", (string)null);

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            DateFrom = new DateOnly(2021, 9, 1),
                            DateTo = new DateOnly(2022, 6, 30),
                            GroupId = 1,
                            ReasonEnd = "Transfer to new group",
                            ReasonStart = "Admission",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            DateFrom = new DateOnly(2022, 9, 1),
                            GroupId = 2,
                            ReasonStart = "Transfer",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 3,
                            DateFrom = new DateOnly(2021, 9, 1),
                            DateTo = new DateOnly(2024, 6, 30),
                            GroupId = 1,
                            ReasonEnd = "Graduation",
                            ReasonStart = "Admission",
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 4,
                            DateFrom = new DateOnly(2022, 9, 1),
                            DateTo = new DateOnly(2023, 1, 15),
                            GroupId = 2,
                            ReasonEnd = "Academic Leave",
                            ReasonStart = "Admission",
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 5,
                            DateFrom = new DateOnly(2023, 9, 1),
                            GroupId = 3,
                            ReasonStart = "Admission",
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 6,
                            DateFrom = new DateOnly(2023, 9, 1),
                            GroupId = 3,
                            ReasonStart = "Transfer",
                            StudentId = 5
                        },
                        new
                        {
                            EnrollmentId = 7,
                            DateFrom = new DateOnly(2024, 9, 1),
                            GroupId = 4,
                            ReasonStart = "Admission",
                            StudentId = 6
                        },
                        new
                        {
                            EnrollmentId = 8,
                            DateFrom = new DateOnly(2022, 9, 1),
                            DateTo = new DateOnly(2025, 6, 30),
                            GroupId = 2,
                            ReasonEnd = "Graduation",
                            ReasonStart = "Admission",
                            StudentId = 7
                        },
                        new
                        {
                            EnrollmentId = 9,
                            DateFrom = new DateOnly(2024, 9, 1),
                            GroupId = 4,
                            ReasonStart = "Admission",
                            StudentId = 8
                        },
                        new
                        {
                            EnrollmentId = 10,
                            DateFrom = new DateOnly(2023, 9, 1),
                            DateTo = new DateOnly(2024, 12, 20),
                            GroupId = 3,
                            ReasonEnd = "Expelled",
                            ReasonStart = "Admission",
                            StudentId = 9
                        },
                        new
                        {
                            EnrollmentId = 11,
                            DateFrom = new DateOnly(2025, 9, 1),
                            GroupId = 5,
                            ReasonStart = "Admission",
                            StudentId = 10
                        },
                        new
                        {
                            EnrollmentId = 12,
                            DateFrom = new DateOnly(2024, 9, 1),
                            GroupId = 4,
                            ReasonStart = "Transfer",
                            StudentId = 11
                        },
                        new
                        {
                            EnrollmentId = 13,
                            DateFrom = new DateOnly(2021, 9, 1),
                            DateTo = new DateOnly(2024, 6, 30),
                            GroupId = 1,
                            ReasonEnd = "Graduation",
                            ReasonStart = "Admission",
                            StudentId = 12
                        },
                        new
                        {
                            EnrollmentId = 14,
                            DateFrom = new DateOnly(2022, 9, 1),
                            DateTo = new DateOnly(2023, 6, 30),
                            GroupId = 2,
                            ReasonEnd = "Transfer to new group",
                            ReasonStart = "Admission",
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentPlanAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("AssignmentId");

                    b.HasIndex("PlanId");

                    b.HasIndex("StudentId");

                    b.ToTable("Student_Plan_Assignment", (string)null);

                    b.HasData(
                        new
                        {
                            AssignmentId = 1,
                            DateFrom = new DateOnly(2021, 9, 1),
                            PlanId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            AssignmentId = 2,
                            DateFrom = new DateOnly(2021, 9, 1),
                            DateTo = new DateOnly(2024, 6, 30),
                            PlanId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            AssignmentId = 3,
                            DateFrom = new DateOnly(2022, 9, 1),
                            PlanId = 2,
                            StudentId = 3
                        },
                        new
                        {
                            AssignmentId = 4,
                            DateFrom = new DateOnly(2023, 9, 1),
                            PlanId = 2,
                            StudentId = 4
                        },
                        new
                        {
                            AssignmentId = 5,
                            DateFrom = new DateOnly(2022, 9, 1),
                            PlanId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            AssignmentId = 6,
                            DateFrom = new DateOnly(2024, 9, 1),
                            PlanId = 2,
                            StudentId = 6
                        },
                        new
                        {
                            AssignmentId = 7,
                            DateFrom = new DateOnly(2022, 9, 1),
                            DateTo = new DateOnly(2025, 6, 30),
                            PlanId = 1,
                            StudentId = 7
                        },
                        new
                        {
                            AssignmentId = 8,
                            DateFrom = new DateOnly(2024, 9, 1),
                            PlanId = 2,
                            StudentId = 8
                        },
                        new
                        {
                            AssignmentId = 9,
                            DateFrom = new DateOnly(2025, 9, 1),
                            PlanId = 2,
                            StudentId = 10
                        },
                        new
                        {
                            AssignmentId = 10,
                            DateFrom = new DateOnly(2024, 9, 1),
                            PlanId = 2,
                            StudentId = 11
                        },
                        new
                        {
                            AssignmentId = 11,
                            DateFrom = new DateOnly(2021, 9, 1),
                            DateTo = new DateOnly(2024, 6, 30),
                            PlanId = 1,
                            StudentId = 12
                        },
                        new
                        {
                            AssignmentId = 12,
                            DateFrom = new DateOnly(2023, 9, 1),
                            DateTo = new DateOnly(2024, 12, 20),
                            PlanId = 1,
                            StudentId = 9
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentSubgroupAssignment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    b.Property<int>("SubgroupId")
                        .HasColumnType("int")
                        .HasColumnName("subgroup_id");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("SubgroupId");

                    b.ToTable("Student_Subgroup_Assignment", (string)null);

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            SubgroupId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            SubgroupId = 3
                        },
                        new
                        {
                            EnrollmentId = 3,
                            SubgroupId = 2
                        },
                        new
                        {
                            EnrollmentId = 6,
                            SubgroupId = 4
                        },
                        new
                        {
                            EnrollmentId = 7,
                            SubgroupId = 5
                        },
                        new
                        {
                            EnrollmentId = 8,
                            SubgroupId = 3
                        },
                        new
                        {
                            EnrollmentId = 9,
                            SubgroupId = 6
                        },
                        new
                        {
                            EnrollmentId = 11,
                            SubgroupId = 7
                        },
                        new
                        {
                            EnrollmentId = 12,
                            SubgroupId = 5
                        },
                        new
                        {
                            EnrollmentId = 13,
                            SubgroupId = 2
                        },
                        new
                        {
                            EnrollmentId = 14,
                            SubgroupId = 3
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudyGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("date")
                        .HasColumnName("date_closed");

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<string>("Faculty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("faculty");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("group_code");

                    b.HasKey("GroupId");

                    b.HasIndex("GroupCode")
                        .IsUnique();

                    b.ToTable("Study_Group", (string)null);

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            DateCreated = new DateOnly(2021, 9, 1),
                            Faculty = "Computer Science",
                            GroupCode = "CS-21"
                        },
                        new
                        {
                            GroupId = 2,
                            DateCreated = new DateOnly(2022, 9, 1),
                            Faculty = "Computer Science",
                            GroupCode = "CS-22"
                        },
                        new
                        {
                            GroupId = 3,
                            DateCreated = new DateOnly(2023, 9, 1),
                            Faculty = "Computer Science",
                            GroupCode = "CS-23"
                        },
                        new
                        {
                            GroupId = 4,
                            DateCreated = new DateOnly(2024, 9, 1),
                            Faculty = "Computer Science",
                            GroupCode = "CS-24"
                        },
                        new
                        {
                            GroupId = 5,
                            DateCreated = new DateOnly(2025, 9, 1),
                            Faculty = "Computer Science",
                            GroupCode = "CS-25"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudyPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("PlanName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("plan_name");

                    b.Property<string>("SpecialtyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("specialty_code");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.HasKey("PlanId");

                    b.ToTable("Study_Plan", (string)null);

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            PlanName = "BSc Computer Science v1",
                            SpecialtyCode = "CS-101",
                            ValidFrom = new DateOnly(2021, 9, 1)
                        },
                        new
                        {
                            PlanId = 2,
                            PlanName = "BSc Computer Science v2",
                            SpecialtyCode = "CS-102",
                            ValidFrom = new DateOnly(2023, 9, 1)
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Subgroup", b =>
                {
                    b.Property<int>("SubgroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subgroup_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubgroupId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("SubgroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("subgroup_name");

                    b.HasKey("SubgroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("Subgroup", (string)null);

                    b.HasData(
                        new
                        {
                            SubgroupId = 1,
                            GroupId = 1,
                            SubgroupName = "Subgroup A"
                        },
                        new
                        {
                            SubgroupId = 2,
                            GroupId = 1,
                            SubgroupName = "Subgroup B"
                        },
                        new
                        {
                            SubgroupId = 3,
                            GroupId = 2,
                            SubgroupName = "Subgroup A"
                        },
                        new
                        {
                            SubgroupId = 4,
                            GroupId = 3,
                            SubgroupName = "Subgroup A"
                        },
                        new
                        {
                            SubgroupId = 5,
                            GroupId = 4,
                            SubgroupName = "Subgroup A"
                        },
                        new
                        {
                            SubgroupId = 6,
                            GroupId = 4,
                            SubgroupName = "Subgroup B"
                        },
                        new
                        {
                            SubgroupId = 7,
                            GroupId = 5,
                            SubgroupName = "Subgroup A"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.AcademicLeave", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudentGroupEnrollment", "Enrollment")
                        .WithMany("AcademicLeaves")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.ExternalTransfer", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudentGroupEnrollment", "Enrollment")
                        .WithMany("ExternalTransfers")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniversityHistory.Domain.Entities.Institution", "Institution")
                        .WithMany("Transfers")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.Student", "Student")
                        .WithMany("ExternalTransfers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Institution");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.GradeRecord", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudentCourseEnrollment", "CourseEnrollment")
                        .WithMany("GradeRecords")
                        .HasForeignKey("CourseEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseEnrollment");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.PlanDiscipline", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.Discipline", "Discipline")
                        .WithMany("PlanDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.StudyPlan", "Plan")
                        .WithMany("PlanDisciplines")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentCourseEnrollment", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudentPlanAssignment", "Assignment")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.Discipline", "Discipline")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentGroupEnrollment", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudyGroup", "Group")
                        .WithMany("Enrollments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentPlanAssignment", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudyPlan", "Plan")
                        .WithMany("PlanAssignments")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.Student", "Student")
                        .WithMany("PlanAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentSubgroupAssignment", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudentGroupEnrollment", "Enrollment")
                        .WithOne("SubgroupAssignment")
                        .HasForeignKey("UniversityHistory.Domain.Entities.StudentSubgroupAssignment", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.Subgroup", "Subgroup")
                        .WithMany("SubgroupAssignments")
                        .HasForeignKey("SubgroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Subgroup");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Subgroup", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudyGroup", "Group")
                        .WithMany("Subgroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Discipline", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("PlanDisciplines");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Institution", b =>
                {
                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("ExternalTransfers");

                    b.Navigation("PlanAssignments");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentCourseEnrollment", b =>
                {
                    b.Navigation("GradeRecords");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentGroupEnrollment", b =>
                {
                    b.Navigation("AcademicLeaves");

                    b.Navigation("ExternalTransfers");

                    b.Navigation("SubgroupAssignment");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentPlanAssignment", b =>
                {
                    b.Navigation("CourseEnrollments");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudyGroup", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Subgroups");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudyPlan", b =>
                {
                    b.Navigation("PlanAssignments");

                    b.Navigation("PlanDisciplines");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Subgroup", b =>
                {
                    b.Navigation("SubgroupAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
