// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityHistory.Infrastructure.Data;

#nullable disable

namespace UniversityHistory.Infrastructure.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    partial class UniversityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityHistory.Domain.Entities.AcademicLeave", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("leave_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("LeaveId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Academic_Leave", (string)null);

                    b.HasData(
                        new
                        {
                            LeaveId = 1,
                            EnrollmentId = 4,
                            Reason = "Medical leave",
                            StartDate = new DateOnly(2023, 1, 16),
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineId"));

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("discipline_name");

                    b.HasKey("DisciplineId");

                    b.ToTable("Discipline", (string)null);

                    b.HasData(
                        new
                        {
                            DisciplineId = 1,
                            DisciplineName = "Calculus I"
                        },
                        new
                        {
                            DisciplineId = 2,
                            DisciplineName = "Introduction to Computer Science"
                        },
                        new
                        {
                            DisciplineId = 3,
                            DisciplineName = "Data Structures"
                        },
                        new
                        {
                            DisciplineId = 4,
                            DisciplineName = "Linear Algebra"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.ExternalTransfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transfer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferId"));

                    b.Property<int?>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("institution_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("notes");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateOnly>("TransferDate")
                        .HasColumnType("date")
                        .HasColumnName("transfer_date");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("transfer_type");

                    b.HasKey("TransferId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("StudentId");

                    b.ToTable("External_Transfers", null, t =>
                        {
                            t.HasCheckConstraint("chk_transfer_type", "transfer_type IN ('In','Out')");
                        });

                    b.HasData(
                        new
                        {
                            TransferId = 1,
                            EnrollmentId = 5,
                            InstitutionId = 2,
                            Notes = "Completed first year at Stanford",
                            StudentId = 4,
                            TransferDate = new DateOnly(2023, 8, 25),
                            TransferType = "In"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.GradeRecord", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<DateOnly>("AssessmentDate")
                        .HasColumnType("date")
                        .HasColumnName("assessment_date");

                    b.Property<int>("AttemptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt_no");

                    b.Property<int>("CourseEnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("course_enrollment_id");

                    b.Property<string>("GradeValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("grade_value");

                    b.HasKey("GradeId");

                    b.HasIndex("CourseEnrollmentId", "AttemptNo")
                        .IsUnique();

                    b.ToTable("Grade_Record", (string)null);

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            AssessmentDate = new DateOnly(2022, 1, 15),
                            AttemptNo = 1,
                            CourseEnrollmentId = 1,
                            GradeValue = "A"
                        },
                        new
                        {
                            GradeId = 2,
                            AssessmentDate = new DateOnly(2022, 1, 18),
                            AttemptNo = 1,
                            CourseEnrollmentId = 2,
                            GradeValue = "B+"
                        },
                        new
                        {
                            GradeId = 3,
                            AssessmentDate = new DateOnly(2022, 1, 15),
                            AttemptNo = 1,
                            CourseEnrollmentId = 3,
                            GradeValue = "A-"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("institution_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("institution_name");

                    b.HasKey("InstitutionId");

                    b.ToTable("Institution", (string)null);

                    b.HasData(
                        new
                        {
                            InstitutionId = 1,
                            City = "Cambridge",
                            Country = "USA",
                            InstitutionName = "MIT"
                        },
                        new
                        {
                            InstitutionId = 2,
                            City = "Stanford",
                            Country = "USA",
                            InstitutionName = "Stanford University"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.PlanDiscipline", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("control_type");

                    b.Property<decimal>("Credits")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("credits");

                    b.Property<int>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("hours");

                    b.Property<int>("SemesterNo")
                        .HasColumnType("int")
                        .HasColumnName("semester_no");

                    b.HasKey("PlanId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("Plan_Disciplines", null, t =>
                        {
                            t.HasCheckConstraint("chk_control_type", "control_type IN ('Exam','Credit','Coursework')");
                        });

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            DisciplineId = 1,
                            ControlType = "Exam",
                            Credits = 4.0m,
                            Hours = 120,
                            SemesterNo = 1
                        },
                        new
                        {
                            PlanId = 1,
                            DisciplineId = 2,
                            ControlType = "Exam",
                            Credits = 5.0m,
                            Hours = 150,
                            SemesterNo = 1
                        },
                        new
                        {
                            PlanId = 1,
                            DisciplineId = 3,
                            ControlType = "Coursework",
                            Credits = 6.0m,
                            Hours = 180,
                            SemesterNo = 2
                        },
                        new
                        {
                            PlanId = 2,
                            DisciplineId = 1,
                            ControlType = "Exam",
                            Credits = 4.0m,
                            Hours = 120,
                            SemesterNo = 1
                        },
                        new
                        {
                            PlanId = 2,
                            DisciplineId = 2,
                            ControlType = "Exam",
                            Credits = 5.0m,
                            Hours = 150,
                            SemesterNo = 1
                        },
                        new
                        {
                            PlanId = 2,
                            DisciplineId = 4,
                            ControlType = "Exam",
                            Credits = 4.0m,
                            Hours = 120,
                            SemesterNo = 2
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'");

                    b.HasKey("StudentId");

                    b.ToTable("Student", null, t =>
                        {
                            t.HasCheckConstraint("chk_student_status", "status IN ('Active','OnLeave','Expelled','Graduated')");
                        });

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            BirthDate = new DateOnly(2003, 5, 14),
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Phone = "555-0101",
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 2,
                            BirthDate = new DateOnly(2002, 11, 2),
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            Phone = "555-0102",
                            Status = "Graduated"
                        },
                        new
                        {
                            StudentId = 3,
                            BirthDate = new DateOnly(2004, 8, 22),
                            Email = "charlie@example.com",
                            FirstName = "Charlie",
                            LastName = "Williams",
                            Phone = "555-0103",
                            Status = "OnLeave"
                        },
                        new
                        {
                            StudentId = 4,
                            BirthDate = new DateOnly(2003, 1, 30),
                            Email = "diana@example.com",
                            FirstName = "Diana",
                            LastName = "Brown",
                            Phone = "555-0104",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentCourseEnrollment", b =>
                {
                    b.Property<int>("CourseEnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("course_enrollment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseEnrollmentId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.Property<int>("SemesterNo")
                        .HasColumnType("int")
                        .HasColumnName("semester_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Planned'");

                    b.HasKey("CourseEnrollmentId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("Student_Course_Enrollment", null, t =>
                        {
                            t.HasCheckConstraint("chk_course_status", "status IN ('Planned','InProgress','Completed','Retake')");
                        });

                    b.HasData(
                        new
                        {
                            CourseEnrollmentId = 1,
                            AssignmentId = 1,
                            DisciplineId = 1,
                            SemesterNo = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 2,
                            AssignmentId = 1,
                            DisciplineId = 2,
                            SemesterNo = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            CourseEnrollmentId = 3,
                            AssignmentId = 2,
                            DisciplineId = 1,
                            SemesterNo = 1,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentGroupEnrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("ReasonEnd")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("reason_end");

                    b.Property<string>("ReasonStart")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("reason_start");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int?>("SubgroupId")
                        .HasColumnType("int")
                        .HasColumnName("subgroup_id");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubgroupId");

                    b.HasIndex("GroupId", "DateFrom")
                        .HasDatabaseName("IX_Enrollment_GroupId_DateFrom");

                    b.ToTable("Student_Group_Enrollment", (string)null);

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            DateFrom = new DateOnly(2021, 9, 1),
                            DateTo = new DateOnly(2022, 6, 30),
                            GroupId = 1,
                            ReasonEnd = "Transfer to new group",
                            ReasonStart = "Admission",
                            StudentId = 1,
                            SubgroupId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            DateFrom = new DateOnly(2022, 9, 1),
                            GroupId = 2,
                            ReasonStart = "Transfer",
                            StudentId = 1,
                            SubgroupId = 3
                        },
                        new
                        {
                            EnrollmentId = 3,
                            DateFrom = new DateOnly(2021, 9, 1),
                            DateTo = new DateOnly(2024, 6, 30),
                            GroupId = 1,
                            ReasonEnd = "Graduation",
                            ReasonStart = "Admission",
                            StudentId = 2,
                            SubgroupId = 2
                        },
                        new
                        {
                            EnrollmentId = 4,
                            DateFrom = new DateOnly(2022, 9, 1),
                            DateTo = new DateOnly(2023, 1, 15),
                            GroupId = 2,
                            ReasonEnd = "Academic Leave",
                            ReasonStart = "Admission",
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 5,
                            DateFrom = new DateOnly(2023, 9, 1),
                            GroupId = 3,
                            ReasonStart = "Admission",
                            StudentId = 4
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentPlanAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("AssignmentId");

                    b.HasIndex("PlanId");

                    b.HasIndex("StudentId");

                    b.ToTable("Student_Plan_Assignment", (string)null);

                    b.HasData(
                        new
                        {
                            AssignmentId = 1,
                            DateFrom = new DateOnly(2021, 9, 1),
                            PlanId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            AssignmentId = 2,
                            DateFrom = new DateOnly(2021, 9, 1),
                            DateTo = new DateOnly(2024, 6, 30),
                            PlanId = 1,
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudyGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("CreationYear")
                        .HasColumnType("int")
                        .HasColumnName("creation_year");

                    b.Property<string>("Faculty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("faculty");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("group_code");

                    b.HasKey("GroupId");

                    b.HasIndex("GroupCode")
                        .IsUnique();

                    b.ToTable("Study_Group", (string)null);

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            CreationYear = 2021,
                            Faculty = "Computer Science",
                            GroupCode = "CS-21"
                        },
                        new
                        {
                            GroupId = 2,
                            CreationYear = 2022,
                            Faculty = "Computer Science",
                            GroupCode = "CS-22"
                        },
                        new
                        {
                            GroupId = 3,
                            CreationYear = 2023,
                            Faculty = "Computer Science",
                            GroupCode = "CS-23"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudyPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("PlanName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("plan_name");

                    b.Property<string>("SpecialtyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("specialty_code");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("int")
                        .HasColumnName("total_credits");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.HasKey("PlanId");

                    b.ToTable("Study_Plan", (string)null);

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            PlanName = "BSc Computer Science v1",
                            SpecialtyCode = "CS-101",
                            TotalCredits = 240,
                            ValidFrom = new DateOnly(2021, 9, 1)
                        },
                        new
                        {
                            PlanId = 2,
                            PlanName = "BSc Computer Science v2",
                            SpecialtyCode = "CS-102",
                            TotalCredits = 240,
                            ValidFrom = new DateOnly(2023, 9, 1)
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Subgroup", b =>
                {
                    b.Property<int>("SubgroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subgroup_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubgroupId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("SubgroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("subgroup_name");

                    b.HasKey("SubgroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("Subgroup", (string)null);

                    b.HasData(
                        new
                        {
                            SubgroupId = 1,
                            GroupId = 1,
                            SubgroupName = "Subgroup A"
                        },
                        new
                        {
                            SubgroupId = 2,
                            GroupId = 1,
                            SubgroupName = "Subgroup B"
                        },
                        new
                        {
                            SubgroupId = 3,
                            GroupId = 2,
                            SubgroupName = "Subgroup A"
                        });
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.AcademicLeave", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudentGroupEnrollment", "Enrollment")
                        .WithMany("AcademicLeaves")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.Student", "Student")
                        .WithMany("AcademicLeaves")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.ExternalTransfer", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudentGroupEnrollment", "Enrollment")
                        .WithMany("ExternalTransfers")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniversityHistory.Domain.Entities.Institution", "Institution")
                        .WithMany("Transfers")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.Student", "Student")
                        .WithMany("ExternalTransfers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Institution");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.GradeRecord", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudentCourseEnrollment", "CourseEnrollment")
                        .WithMany("GradeRecords")
                        .HasForeignKey("CourseEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseEnrollment");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.PlanDiscipline", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.Discipline", "Discipline")
                        .WithMany("PlanDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.StudyPlan", "Plan")
                        .WithMany("PlanDisciplines")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentCourseEnrollment", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudentPlanAssignment", "Assignment")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.Discipline", "Discipline")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentGroupEnrollment", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudyGroup", "Group")
                        .WithMany("Enrollments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.Subgroup", "Subgroup")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubgroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("Student");

                    b.Navigation("Subgroup");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentPlanAssignment", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudyPlan", "Plan")
                        .WithMany("PlanAssignments")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversityHistory.Domain.Entities.Student", "Student")
                        .WithMany("PlanAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Subgroup", b =>
                {
                    b.HasOne("UniversityHistory.Domain.Entities.StudyGroup", "Group")
                        .WithMany("Subgroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Discipline", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("PlanDisciplines");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Institution", b =>
                {
                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Student", b =>
                {
                    b.Navigation("AcademicLeaves");

                    b.Navigation("Enrollments");

                    b.Navigation("ExternalTransfers");

                    b.Navigation("PlanAssignments");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentCourseEnrollment", b =>
                {
                    b.Navigation("GradeRecords");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentGroupEnrollment", b =>
                {
                    b.Navigation("AcademicLeaves");

                    b.Navigation("ExternalTransfers");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudentPlanAssignment", b =>
                {
                    b.Navigation("CourseEnrollments");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudyGroup", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Subgroups");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.StudyPlan", b =>
                {
                    b.Navigation("PlanAssignments");

                    b.Navigation("PlanDisciplines");
                });

            modelBuilder.Entity("UniversityHistory.Domain.Entities.Subgroup", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
